'use client';
/**
 * use-live-telemetry.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Real-time flows + alerts hook.
 *
 * Standalone / GitHub Pages mode:
 *   Subscribes to the mock-engine's pub-sub system. Flows and alerts are
 *   generated by the in-browser simulation timer (every 1.5s).
 *
 * Local / production mode:
 *   Connects to the FastAPI SSE stream at GET /api/events.
 */

import { useState, useEffect, useCallback } from 'react';
import type { Flow, Alert } from '@/types';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

function isStandalone(): boolean {
  if (process.env.NEXT_PUBLIC_STANDALONE === 'true') return true;
  if (typeof window !== 'undefined') {
    const host = window.location.hostname;
    if (host.endsWith('github.io') || host === 'localhost.local') return true;
  }
  return false;
}

export function useLiveTelemetry() {
  const [liveFlows, setLiveFlows]   = useState<Flow[]>([]);
  const [liveAlerts, setLiveAlerts] = useState<Alert[]>([]);
  const [connected, setConnected]   = useState(false);

  useEffect(() => {
    if (isStandalone()) {
      // ── Mock mode: subscribe to in-browser simulation ──────────────────────
      let unsubFlow: (() => void) | null = null;
      let unsubAlert: (() => void) | null = null;

      import('@/lib/mock-engine').then(mod => {
        mod.startSimulation();
        setConnected(true);

        unsubFlow = mod.subscribeFlows((flow) => {
          setLiveFlows(prev => [flow, ...prev].slice(0, 50));
        });

        unsubAlert = mod.subscribeAlerts((alert) => {
          setLiveAlerts(prev => [alert, ...prev].slice(0, 20));
        });
      });

      return () => {
        unsubFlow?.();
        unsubAlert?.();
      };
    } else {
      // ── Real mode: SSE from FastAPI backend ────────────────────────────────
      const es = new EventSource(`${API_BASE}/api/events`);
      es.onopen  = () => setConnected(true);
      es.onerror = () => setConnected(false);

      es.addEventListener('new_flow', (e: MessageEvent) => {
        try {
          const flow = JSON.parse(e.data) as Flow;
          setLiveFlows(prev => [flow, ...prev].slice(0, 50));
        } catch { /* ignore parse errors */ }
      });

      es.addEventListener('new_alert', (e: MessageEvent) => {
        try {
          const alert = JSON.parse(e.data) as Alert;
          setLiveAlerts(prev => [alert, ...prev].slice(0, 20));
        } catch { /* ignore parse errors */ }
      });

      return () => es.close();
    }
  }, []);

  const clearFlows  = useCallback(() => setLiveFlows([]),  []);
  const clearAlerts = useCallback(() => setLiveAlerts([]), []);

  return { liveFlows, liveAlerts, connected, clearFlows, clearAlerts };
}
